---
routes:
  - path: "/"
    name: Home
    components:
      maincontent: SQLEditorLayout
      connections: ConnectionInfo
    props:
      maincontent:
        - name: Home
      connections:
        - name: Connections
    children:
      - path: ''
        components:
          default: DefaultView
          barchart: Barchart

  - path: "/connections"
    name: Connections
    components:
      default: ConnectionInfo
    props:
      default:
        - name: Home

  - path: "/connection/:id"
    name: Connection
    components:
      maincontent: SQLEditorLayout
      connections: ConnectionInfo
    props:
      maincontent:
        - name: Home
      connections:
        - name: Connections

  - path: "/schema/:id"
    name: Schema
    components:
      maincontent: SQLEditorLayout
      connections: ConnectionInfo
    props:
      maincontent:
        - name: Home
      connections:
        - name: Connections

  - path: "/table/:id"
    name: Table
    components:
      maincontent: SQLEditorLayout
      connections: ConnectionInfo
    props:
      maincontent:
        - name: Home
      connections:
        - name: Connections

  - path: "/inspector/table/:table/row/:id"
    name: Dataset
    components:
      maincontent: DynamicConfigurableComponent
      connections: ConnectionInfo
    props:
      maincontent:
        - id: Home
        - table: table
      connections:
        - name: Connections
