---
routes:
  - path: "/"
    name: Home
    components:
      maincontent: SQLEditorLayout
      connections: ConnectionInfo
    children:
      - path: ''
        components:
          default: DefaultView
          barchart: Barchart
    props: true

