---
routes:
  - path: "/"
    name: Home
    components:
      maincontent: SQLEditorLayout
      connections: () => import('@/components/ConnectionInfo')
    children:
      - path: ''
        components:
          default: DefaultView
          barchart: Barchart')
    props: true

